Add mapping url that returns block number for the given slot number.
availproject/bridge-api pull request #1
Opened 2024-02-14 17:12 UTC by 0xSasaPrsic

Add url that maps given slot to block number. It uses beaconcha api to fetch block info.

2024-02-14 20:50 UTC, QEDK requested changes
Some minor changes, lmk.

2024-02-14 20:50 UTC, QEDK commented on src/main.rs
> +    beaconcha_url: String,
Should be `beaconchain_base_url` I think `.in` doman is part of the service's name.

2024-02-14 20:50 UTC, QEDK commented on src/main.rs
> +        .succinct_client
Let's rename `succinct_client` to `reqwest_client`?

2024-02-14 20:50 UTC, QEDK commented on src/main.rs
> +#[derive(Deserialize, Serialize, Debug)]
Any reason we need `Debug`?

2024-02-15 22:19 UTC, 0xSasaPrsic commented on src/main.rs
> +#[derive(Deserialize, Serialize, Debug)]
Not needed, deleting.

2024-02-15 23:13 UTC, QEDK approved these changes
LGTM.

2024-02-15 23:14 UTC, merged