feat: Adds custom max concurrent request on jsonrpsee http client
availproject/bridge-api pull request #17
Opened 2024-05-23 12:07 UTC by moraesjeremias

# Problem Statement
jsonrpsee lib has a default 256 maximum concurrent rpc requests on its http client. See reference below.
In load test scenarios we caught 20k errors due to maximum concurrent slots field in the HTTP client.

## Proposal
- Introduce a configurable/dynamic max_concurrent_request var to correctly build/construct the HTTP client with accordingly specs.

## To be tested
- Load with customized max concurrent request values (256, 512, 1024)
- Resource consumption on higher max concurrent request values.

2024-06-03 11:56 UTC, QEDK requested changes
Nit.

2024-06-03 11:56 UTC, QEDK commented on src/main.rs
> +            .max_concurrent_requests(max_concurrent_request)
Can be changed to `1024` requests.

2024-06-03 23:19 UTC, moraesjeremias commented on src/main.rs
> +            .max_concurrent_requests(max_concurrent_request)
Done :white_check_mark:

2024-06-04 07:06 UTC, QEDK approved these changes
LGTM.

2024-06-04 07:06 UTC, merged